# Generated by Django 4.1.7 on 2023-03-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
